BTW THIS IS A COMMENT
OBTW
SOMETHING
TLDR
HAI

VISIBLE EITHER OF ALL OF WIN AN WIN AN FAIL MKAY AN WIN
VISIBLE BOTH OF WIN AN ANY OF WIN AN WIN AN FAIL MKAY
VISIBLE BOTH OF WIN AN ANY OF 3 AN 2 AN 1 MKAY EITHER OF ALL OF WIN AN WIN AN "WOW" MKAY AN WIN

VISIBLE BOTH OF WIN AN
VISIBLE BOTH OF WIN AN "FAIL"
VISIBLE BOTH OF 1 AN "FAIL"
VISIBLE EITHER OF var1 AN var1
VISIBLE BOTH OF WIN AN ""
VISIBLE SUM OF "1" AN "2"
VISIBLE SUM OF WIN AN "2"
VISIBLE SUM OF FAIL AN "2"
KTHXBYE