BTW boolean syntax checker
HAI
	I HAS A x ITZ WIN 
	I HAS A y ITZ FAIL
	I HAS A z ITZ FAIL

	BOTH OF x AN AN x MKAY
	ALL OF NOT x AN BOTH OF y AN z AN EITHER OF x AN y 
	ALL OF ALL OF x AN y MKAY AN z MKAY 

	BOTH OF NOT WIN AN NOT WIN
	VISIBLE IT
	EITHER OF NOT WIN AN WIN
	VISIBLE IT
	WON OF BOTH OF WIN AN WIN AN EITHER OF WIN AN FAIL
	VISIBLE IT
	ALL OF WIN AN BOTH OF WIN AN NOT FAIL AN WIN AN WON OF WIN AN NOT WIN
	VISIBLE IT
KTHXBYE