BTW TYPECASTING BONUS

HAI

BTW WIN = 1 AND FAIL = 0 (1+0)
VISIBLE SUM OF WIN AN FAIL 

BTW TYPECAST STRING TO INT
VISIBLE SUM OF "2" AN "3.0"

BTW EMPTY STRING/NOOB = FAIL
VISIBLE BOTH OF "" AN WIN

VISIBLE BOTH OF NOOB AN WIN

I HAS A var

VISIBLE BOTH OF var AN WIN

BTW ANY STRING = WIN
VISIBLE BOTH OF "HEY" AN WIN

BTW 0 = FAIL, 1 ONWARDS = WIN
VISIBLE EITHER OF 1 AN 0

KTHXBYE