HAI 1.2
	I HAS A NUM ITZ 2		BTW NUM = 2
	I HAS A FLOT ITZ 2.5	BTW FLOT = 2.5
	I HAS A NAME ITZ "erika"	BTW NAME = "erika"

BTW printing values
	VISIBLE NUM
	VISIBLE FLOT
	VISIBLE NAME

BTW assignment statement:
	NUM R 17
	
	VISIBLE "NUM is now " NUM

KTHXBYE
