BTW SYNTAX CHECKER FOR ARITHMETIC
HAI
  DIFF OF
  VISIBLE IT
  SUM OF 7 AN "7" DIFF OF 7 AN "7"
  VISIBLE IT
  SUM OF 23 AN AN 24
  VISIBLE IT
  SUM OF PRODUKT OF 3 AN 5 AN BIGGR OF DIFF OF 17 AN 2 AN 5
  VISIBLE IT
  BIGGR OF PRODUKT OF 11 AN 2 AN QUOSHUNT OF SUM OF 3 AN 5 AN 2
  VISIBLE IT
KTHXBYE
