BTW comparison syntax checker
HAI
	BOTH SAEM 16 AN AN
	BOTH SAEM 
	BOTH SAEM 12 AN

	DIFFRINT 2 AN BIGGR OF 1 AN 2
	VISIBLE IT
	DIFFRINT BIGGR OF 1 AN 2 AN SMALLR OF 3 AN 2
	VISIBLE IT
	DIFFRINT BOTH SAEM 1 AN 2 AN DIFFRINT 1 AN 2
	VISIBLE IT
KTHXBYE